### PR TITLE
Fix prefix support

### LINKED ISSUE #1: Restrict middleware execution to a certain path(s)
As titled: 
Related to https://github.com/fastify/fastify/issues/55

Could be a good idea implement this?
At a first look I don't think it will have a sensible impact on performances.

Example:
```js
fastify.use('/assets', serveStatic(`${__dirname}/dist`))
// could be an array of paths as well
fastify.use(['/assets', '/public'], serveStatic(`${__dirname}/dist`))
```

cc @mcollina @cedmax

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #1.

I still need to check the benchmark, but I might be short on time.
@delvedor can you do that?

### CODE REVIEW

File: middie.js [hunk 1]
```diff
@@ -64,12 +77,17 @@ function middie (complete) {
       } else {
         const middleware = middlewares[i]
         const fn = middleware.fn
-        if (!middleware.path) {
-          fn(req, res, that.done)
-        } else if (middleware.wildcard && pathMatchWildcard(url, middleware.path)) {
-          fn(req, res, that.done)
-        } else if (middleware.path === url || (typeof middleware.path !== 'string' && middleware.path.indexOf(url) > -1)) {
+        const regexp = middleware.regexp
```
Comment (delvedor) [inline middie.js]: I think here and above we could just use `var`.

Comment (mcollina) [reply middie.js]: updated

**Comment by mcollina** [comment]
Side note, this is a semver-major change.
